### ISSUE TITLE
'Failed to terminate a thread' on closing wxHE

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#28] opened 2017-02-07 15:41 UTC
Hello!

version: 0.24 on openSUSE.

Got a 'Failed to terminate a thread' error message on closing wxHE after having manipulations with the second file.

Steps-to-reproduce algo: https://www.youtube.com/watch?v=Lb1mnX_0_0k

**Comment by EUA** [comment] 2017-02-09 02:41
Yeah it's known bug.
It's from scroll thread code.
Somehow, it resist to die.
_Might, scientist could find eternal life from my code..._

**Comment by EUA** [comment] 2017-02-18 01:42
R.I.P. in ec65334

**Comment by MikhailKasimov** [comment] 2017-02-22 00:37
If I haven't messed myself among wxH revisions, for wxhexeditor-0.23+git20170218-31.2 this issue is still alive: https://www.youtube.com/watch?v=14iKKzDhaAY

**Comment by MikhailKasimov** [comment] 2017-02-22 09:31
UTR with wxH: 0.23+git20170221-36.1

**Comment by verbaska** [comment] 2017-07-29 11:42
There certainly was a problem in WxWidgets' thread.h file. At least, I don't find their flow orthodox.

WxHexEditor source code used a class from the thread.h header called wxThreadHelper.  Its method KillThread() called the dangerous method m_thread->Kill(), which is not recommended by WxWidgets.

Instead of that, I used the Delete() method, which is considered safe. I don't find any reason to use the Kill() method. Now I have compiled WxHexEditor with this fix and it works like a charm.

Below you can see my proposed fix:

`class WXDLLIMPEXP_BASE wxThreadHelper
{
private:
    void KillThread()
    {
        if ( m_thread )
        {
            m_thread->Delete();
            delete m_thread;
        }
    }`

**Comment by EUA** [comment] 2017-08-08 02:35
Hi @verbaska 
Thanks for clarification.
Indeed it has to be fixed under "wxThreadHelper" class.
I need to fill bugreport form.
But we could use this for now.
ReOpened issue for check it.
Will fix this soon.

**Comment by verbaska** [comment] 2017-08-08 16:53
Good luck ;)

**Comment by EUA** [comment] 2017-08-09 02:29
Since scrollthread:wxThreadHelper is only thread code on wxHexEditor, problem has to arise from here.

As I understand from @MikhailKasimov video, It's only appears on closing wxHexEditor directly while a file is open. But that call need to be lower sections and program needs to close all files before close. 

As @verbaska indicated, it's due wxHelperThread issue. When wxHelperThread destructor runs, it calls KillThread()
```    virtual ~wxThreadHelper() { KillThread(); } ```

We cannot implement @verbaska 's proposed solution here since it's need to be implemented in wxWidgets library. We only can try to do work-a-rounds.

But since we delete the thread before wxThreadHelper's destructor, on scrollthread::Exit(),  by GetThread()->Delete(), there is nothing to delete by KillThread() indeed. So this error must not be true.

I can NOT reproduce it. But find something might be related. When I close files, Debug line just show this error somehow:
`"05:24:53: Debug: In file ./src/unix/threadpsx.cpp at line 261: 'pthread_mutex_destroy()' failed with error 0x00000010 (Device or resource busy)."

If you find any reliable way to re-produce the error, I try to solve it.
But current state, I cannot. I open and close 20 times without success.
(I use wx 3.1 version)

**Closed** 2018-01-01 01:07 UTC
Labels: bug

**Comment by zhenelzuar** [comment] 2018-01-01 07:20
Congrats :)
