### ISSUE TITLE
Cannot save, require 8.1 GB, available 'not available'

### ISSUE THREAD

**Issue by realtebo** [EUA/wxHexEditor#112] opened 2018-07-10 21:41 UTC
It seems that wxHexEditor cannot calculate free space on my SSD, but I've more than 140 GB free

**Comment by neuoy** [comment] 2018-11-06 08:49
This seems to be a duplicate of #108. I have the same issue on Windows 10.

**Closed** 2019-09-22 22:01 UTC
Labels: duplicate
