### ISSUE TITLE
Seg fault wxHexEditor on command line with -- or any non file related character 

### ISSUE THREAD

**Issue by plater** [EUA/wxHexEditor#40] opened 2017-02-19 12:21 UTC
Entering wxHexEditor --help or any non file related character on the command line results in a segmentation fault and core dump.
This issue is found in revision#ec653348e2f59f374a0a0e71e4ea6d97faa6a990
It brings up a message box and if you close the message box and exit immediately the seg fault happens. However if you load a file wxHexEditor functions as expected.

**Comment by MikhailKasimov** [comment] 2017-02-19 13:23
I suppose, wxH should handle ```--help``` and ```--version``` terminal command in similar way and display brief help-info, instead of trying to open some file.

For example: ```wxHexEditor --version|--help``` will output:

```wxhexeditor-%{version}+git%{date}-31.1

wxHexEditor is a hex-editor for HUGE files and devices.

© 2006-2017 Erdem U. Altinyurt

Written by: Erdem U. Altinyurt
Artwork by: Vlad Adrian

Web-site: http://www.wxhexeditor.org/

Bug-reporting: https://github.com/EUA/wxHexEditor/

License: This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation version 2 of the License.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
```

Long story short: both ```--help``` and ```--version``` keys should display the same user can get via 'Help' -> 'About' in GUI, but in command line.

**Comment by EUA** [comment] 2017-02-20 03:11
`./wxHexEditor --help`
gives me no seg fault, but just :

> File does not exists at path:
> --version

don't understand why it give you seg fault.

**Comment by EUA** [comment] 2017-02-20 03:13
Duplicate of #36 
Closed. Please continue from that.

**Closed by EUA** 2017-02-20 03:13 UTC
Labels: duplicate
