### ISSUE TITLE
Lame 'Destination' field on Device Image Tools {Restore, Erase}

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#33] opened 2017-02-15 11:15 UTC
Hello!

Subj

![2017-02-15_13-12-46](https://cloud.githubusercontent.com/assets/7167300/22972043/a875a3be-f380-11e6-815c-2d161922173a.png)

![2017-02-15_13-12-08](https://cloud.githubusercontent.com/assets/7167300/22972056/b0f241dc-f380-11e6-9470-1cbc012bbc61.png)

DE: XFCE 4.12

**Comment by EUA** [comment] 2017-02-18 00:39
Duplicate of #32

**Closed by EUA** 2017-02-18 00:39 UTC
Labels: duplicate
