### ISSUE TITLE
save as doesn't work (Not enough space, when there is plenty of space)

### ISSUE THREAD

**Issue by cieplutki** [EUA/wxHexEditor#108] opened 2018-05-31 21:28 UTC
Hey.
I have this issue, or two:
- when open a file that is bigger than (roughly) 55MB it's always in read only mode. I don't know why is that but if it's because of size first I should be informed and second why modifying in place is not allowed?
- when I try to save as new file it _always_ says "There are not enough free disk space. Required XX KB. Available: Not available." This one regardless of size - whether it's 50MB, 50KB or 50 bytes it's still the same.
What can I do to make it work?

**Comment by westlabill** [comment] 2018-07-22 17:37
First thanks for your efforts in creating what will be an awesome Hex editor.  
Same SaveAs issue here where it says there isn't enough disk space to save a 39K file.  Using Win10 professional.  I tested it on myDocuments folder to see if it were a permissions issue but it didn't matter  where I was trying to save it.  Save creates the appearance of saving but the file remains unmodified.  I don't know where it's being saved to with the save feature.

Hope this helps,  Bill

**Comment by EUA** [comment] 2019-11-15 18:50
duplicate of #98

**Closed by EUA** 2019-11-15 18:50 UTC
Labels: bug, duplicate
